# Generated by Django 3.2 on 2021-05-01 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterconduit',
            name='conduit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.conduit'),
        ),
    ]
