# Generated by Django 3.2 on 2021-05-01 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_characterconduit_conduit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.achievement'),
        ),
    ]
