# Generated by Django 3.2 on 2021-05-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_characterachievement_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='achievements_completed',
            field=models.ManyToManyField(blank=True, default=None, to='api.Achievement'),
        ),
    ]
