# Generated by Django 3.2 on 2021-05-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_character_achievements_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='max_2v2_rating',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='max_3v3_rating',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='max_rbg_rating',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
