# Generated by Django 3.2 on 2021-05-02 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210502_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='max_5v5_rating',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
