# Generated by Django 3.2 on 2021-05-02 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_character_max_5v5_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='date_added',
            new_name='last_update',
        ),
    ]
