# Generated by Django 3.2 on 2021-05-03 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210503_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvpseasonreward',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.region'),
        ),
    ]
