# Generated by Django 3.2 on 2021-05-03 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_pvpseasonreward_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pvpseason',
            name='leaderboards',
        ),
        migrations.AddField(
            model_name='pvpleaderboard',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pvpseason'),
        ),
        migrations.AlterField(
            model_name='character',
            name='alters',
            field=models.ManyToManyField(blank=True, default=None, related_name='_api_character_alters_+', to='api.Character'),
        ),
    ]
