# Generated by Django 3.2 on 2021-05-03 22:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_pvpseason_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pvpleaderboard',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='pvpentry',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
