from . import wowpvp

# wowpvp.update_realms()
# wowpvp.update_classes()
# wowpvp.update_races()
# wowpvp.update_specs()
# wowpvp.update_talents()
# wowpvp.update_pvp_talents()
# wowpvp.update_achievements()
# wowpvp.update_covenant()
# wowpvp.update_soulbinds()
# wowpvp.update_soulbinds_traits()
# wowpvp.update_conduit()
# wowpvp.update_pvp_seasons()
wowpvp.get_archives()
#wowpvp.get_entries()
